openapi: 3.0.0
servers:
  - url: 'https://q57avcvkd3.execute-api.eu-west-1.amazonaws.com/dev'
info:
  title: REST based Product API
  description: A Product API for interacting with the Stonemasons Tools Store backend server
  version: dev

tags:
  - name: Product
    description: |
      This model represents a Product type and is used to retrieve, create or update a product catalog information.

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of Product
          example: Carbide-Hand-Chisel
        title:
          type: string
          description: Product name
          example: Carbide Hand Chisel
        description:
          type: string
          description: Description of Product
          example: Use the Hand Chisel for general stone shaping and roughing out applications.
        weight: 
          type: integer
          description: Weight of Product in grams
          example: 450
        img: 
          type: string
          description: Link to main Product picture
          example: https://i.pinimg.com/originals/fb/83/1c/fb831c528d9dbed9a15b6d96d651594a.jpg
        creationDate:
          type: string
          description: Date of Product creation.
          example: '2020-10-09'
        price:
          type: integer
          description: Price of Product in $
          example: 57
        count:
          type: integer
          description: stock amount of Product
          example: 453
         
  requestBodies:
    Product:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
      description: Product object that needs to be created or updated
      required: true

paths:
  /products:
    get:
      summary: Get list of all Products
      operationId: getProductsList
      tags:
        - Product
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        default:
          description: successful operation
    post:
      tags:
        - Product
      summary: Create a new Product
      operationId: createProduct
      requestBody:
        $ref: "#/components/requestBodies/Product"
      responses:
        '201':
          description: Success product creation responce
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags:
        - Product
      summary: Returns a particular Product
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: ID of Product to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success responce
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - Product
      summary: Update a particular Product
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: ID of Product to be updated
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/Product"
      responses:
        '200':
          description: Success responce
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

